CREATE PROCEDURE ThemTuyenBay
    @MTB VARCHAR(20),
    @TP1 VARCHAR(50),
    @TP2 VARCHAR(50)
AS
BEGIN
    INSERT INTO TUYENBAY (MTB, TP1, TP2)
    VALUES (@MTB, @TP1, @TP2)
END;
GO

CREATE PROCEDURE ThemChuyenBay
    @SH_CB VARCHAR(20),
    @GIO_BAY DATETIME,
    @GIO_DEN DATETIME,
    @GIA_VE DECIMAL(10, 2),
    @GG FLOAT,
    @LG_VE_MAX INT,
    @MTB VARCHAR(20)
AS
BEGIN
    INSERT INTO CHUYENBAY (SH_CB, GIO_BAY, GIO_DEN, GIA_VE, GG, LG_VE_MAX, MTB)
    VALUES (@SH_CB, @GIO_BAY, @GIO_DEN, @GIA_VE, @GG, @LG_VE_MAX, @MTB)
END;
GO

CREATE PROCEDURE ThemThucHien
    @SH_CB VARCHAR(20),
    @NGAY DATE,
    @LG_VE_MAX INT
AS
BEGIN
    INSERT INTO THUCHIEN (SH_CB, NGAY, LG_VE_MAX)
    VALUES (@SH_CB, @NGAY, @LG_VE_MAX)
END;
GO

CREATE PROCEDURE ThemKM
    @SH_DOT VARCHAR(20),
    @NGAY_HL DATE,
    @TG_HL DATE,
    @MTB VARCHAR(20)
AS
BEGIN
    INSERT INTO KM (SH_DOT, NGAY_HL, TG_HL, MTB)
    VALUES (@SH_DOT, @NGAY_HL, @TG_HL, @MTB)
END;
GO

CREATE PROCEDURE ThemKM_CB
    @SH_DOT VARCHAR(20),
    @SH_CB VARCHAR(20),
    @GIA_VE_KM DECIMAL(10, 2)
AS
BEGIN
    INSERT INTO KM_CB (SH_DOT, SH_CB, GIA_VE_KM)
    VALUES (@SH_DOT, @SH_CB, @GIA_VE_KM)
END; 
GO

CREATE PROCEDURE ThemAD_TB
    @MTB VARCHAR(20),
    @SH_DOT VARCHAR(20),
    @MA_ADTB VARCHAR(50)
AS
BEGIN
    INSERT INTO AD_TB (MTB, SH_DOT, MA_ADTB)
    VALUES (@MTB, @SH_DOT, @MA_ADTB)
END;
GO

CREATE PROCEDURE ThemAD_CB
    @SH_CB VARCHAR(20),
    @SH_DOT VARCHAR(20),
    @GIA_VE_KM INT,
    @MA_ADCB VARCHAR(50)
AS
BEGIN
    INSERT INTO AD_CB (SH_CB, SH_DOT, GIA_VE_KM, MA_ADCB)
    VALUES (@SH_CB, @SH_DOT, @GIA_VE_KM, @MA_ADCB)
END;