CREATE DATABASE QLCB
--GO

USE QLCB
--GO 


CREATE TABLE TUYENBAY (
    MTB VARCHAR(20) PRIMARY KEY NOT NULL,
    TP1 VARCHAR(50) NOT NULL,
    TP2 VARCHAR(50) NOT NULL
);

CREATE TABLE CHUYENBAY (
    SH_CB VARCHAR(20) PRIMARY KEY NOT NULL,
    GIO_BAY DATETIME NOT NULL,
    GIO_DEN DATETIME NOT NULL,
    GIA_VE DECIMAL(10, 2) NOT NULL,
    GG FLOAT CHECK (GG >= 0 AND GG <=0.3),
    LG_VE_MAX INT NOT NULL CHECK (LG_VE_MAX >0),
    MTB VARCHAR(20) NOT NULL,
	CONSTRAINT CHK_GB_GD CHECK (GIO_BAY < GIO_DEN)
);

ALTER TABLE CHUYENBAY
ADD CONSTRAINT FK_CHUYENBAY_TUYENBAY 
FOREIGN KEY (MTB) REFERENCES TUYENBAY(MTB);


CREATE TABLE THUCHIEN (
    SH_CB VARCHAR(20) NOT NULL,
    NGAY DATE,
    LG_VE_MAX INT NOT NULL CHECK (LG_VE_MAX >0)
);

ALTER TABLE THUCHIEN 
ADD CONSTRAINT FK_TH_CB
FOREIGN KEY (SH_CB) REFERENCES CHUYENBAY(SH_CB);


CREATE TABLE KM (
    SH_DOT VARCHAR(20) PRIMARY KEY,
    NGAY_HL DATE NOT NULL,
    TG_HL INT NOT NULL CHECK (TG_HL >0),
    MTB VARCHAR(20) NOT NULL
);

ALTER TABLE KM
ADD CONSTRAINT FK_KM_TB
FOREIGN KEY (MTB) REFERENCES TUYENBAY(MTB);


CREATE TABLE KM_CB (
    SH_DOT VARCHAR(20),
    SH_CB VARCHAR(20) NOT NULL,
    GIA_VE_KM DECIMAL(10, 2)
);

ALTER TABLE KM_CB 
ADD CONSTRAINT FK_KM_KMCB 
FOREIGN KEY (SH_DOT) REFERENCES KM(SH_DOT);

ALTER TABLE KM_CB 
ADD CONSTRAINT FK_KM_CB 
FOREIGN KEY (SH_CB) REFERENCES CHUYENBAY(SH_CB);


CREATE TABLE AD_TB (
    MTB VARCHAR(20) NOT NULL,
	SH_DOT VARCHAR(20),
	MA_ADTB VARCHAR(50) PRIMARY KEY NOT NULL
);

ALTER TABLE AD_TB
ADD CONSTRAINT FK_AD_TB
FOREIGN KEY (MTB) REFERENCES TUYENBAY(MTB);

ALTER TABLE AD_TB
ADD CONSTRAINT FK_AD_TB_KM
FOREIGN KEY (SH_DOT) REFERENCES KM(SH_DOT);


CREATE TABLE AD_CB(
    SH_CB VARCHAR(20) NOT NULL,
	SH_DOT VARCHAR(20),
	GIA_VE_KM INT ,
	MA_ADCB VARCHAR(50) PRIMARY KEY NOT NULL
);

ALTER TABLE AD_CB
ADD CONSTRAINT FK_AD_CB
FOREIGN KEY (SH_CB) REFERENCES CHUYENBAY(SH_CB);

ALTER TABLE AD_CB
ADD CONSTRAINT FK_AD_CB_KM
FOREIGN KEY (SH_DOT) REFERENCES KM(SH_DOT);
