CREATE PROCEDURE SuaTuyenBay
    @MTB VARCHAR(20),
    @TP1 VARCHAR(50),
    @TP2 VARCHAR(50)
AS
BEGIN
    UPDATE TUYENBAY
    SET TP1 = @TP1,
        TP2 = @TP2
    WHERE MTB = @MTB
END;
GO

CREATE PROCEDURE SuaChuyenBay
    @SH_CB VARCHAR(20),
    @GIO_BAY DATETIME,
    @GIO_DEN DATETIME,
    @GIA_VE DECIMAL(10, 2),
    @GG FLOAT,
    @LG_VE_MAX INT,
    @MTB VARCHAR(20)
AS
BEGIN
    UPDATE CHUYENBAY
    SET GIO_BAY = @GIO_BAY,
        GIO_DEN = @GIO_DEN,
        GIA_VE = @GIA_VE,
        GG = @GG,
        LG_VE_MAX = @LG_VE_MAX,
        MTB = @MTB
    WHERE SH_CB = @SH_CB
END;
GO

CREATE PROCEDURE SuaThucHien
    @SH_CB VARCHAR(20),
    @NGAY DATE,
    @LG_VE_MAX INT
AS
BEGIN
    UPDATE THUCHIEN
    SET NGAY = @NGAY,
        LG_VE_MAX = @LG_VE_MAX
    WHERE SH_CB = @SH_CB
END;
GO

CREATE PROCEDURE SuaKM
    @SH_DOT VARCHAR(20),
    @NGAY_HL DATE,
    @TG_HL DATE,
    @MTB VARCHAR(20)
AS
BEGIN
    UPDATE KM
    SET NGAY_HL = @NGAY_HL,
        TG_HL = @TG_HL,
        MTB = @MTB
    WHERE SH_DOT = @SH_DOT
END;
GO

CREATE PROCEDURE SuaKM_CB
    @SH_DOT VARCHAR(20),
    @SH_CB VARCHAR(20),
    @GIA_VE_KM DECIMAL(10, 2)
AS
BEGIN
    UPDATE KM_CB
    SET GIA_VE_KM = @GIA_VE_KM
    WHERE SH_DOT = @SH_DOT AND SH_CB = @SH_CB
END;
GO

CREATE PROCEDURE SuaAD_TB
    @MTB VARCHAR(20),
    @SH_DOT VARCHAR(20),
    @MA_ADTB VARCHAR(50)
AS
BEGIN
    UPDATE AD_TB
    SET MTB = @MTB,
        SH_DOT = @SH_DOT
    WHERE MA_ADTB = @MA_ADTB
END;
GO

CREATE PROCEDURE SuaAD_CB
    @SH_CB VARCHAR(20),
    @SH_DOT VARCHAR(20),
    @GIA_VE_KM INT,
    @MA_ADCB VARCHAR(50)
AS
BEGIN
    UPDATE AD_CB
    SET SH_CB = @SH_CB,
        SH_DOT = @SH_DOT,
        GIA_VE_KM = @GIA_VE_KM
    WHERE MA_ADCB = @MA_ADCB
END;